import { defineStore } from 'pinia';

// This is where we keep track of both carts, the associated customer, and applied discounts
// These values and actions can be accessed by importing { useMainStore }

export const useMainStore = defineStore('main', {
  state: () => ({
    cart_delivery: {
      billing_address_id: '',
      completed_at: '',
      context: {},
      created_at: '',
      customer_id: '',
      deleted_at: '',
      email: '',
      id: '',
      idempotency_key: '',
      metadata: {},
      payment_authorized_at: '',
      payment_id: '',
      payment_session: {},
      region_id: '',
      shipping_address_id: '',
      type: '',
      updated_at: '',
      billing_address: {},
      shipping_address: {},
      items: [],
      region: {},
      discounts: [],
      gift_cards: [],
      customer: {},
      payment_sessions: [],
      payment: {},
      shipping_methods: [],
      sales_channel_id: '',
      sales_channel: {},
      shipping_total: 0,
      discount_total: 0,
      raw_discount_total: 0,
      item_tax_total: 0,
      shipping_tax_total: 0,
      tax_total: 0,
      refunded_total: 0,
      total: 0,
      subtotal: 0,
      refundable_amount: 0,
      gift_card_total: 0,
      gift_card_tax_total: 0,
    },
    cart_pickup: {
      billing_address_id: '',
      completed_at: '',
      context: {},
      created_at: '',
      customer_id: '',
      deleted_at: '',
      email: '',
      id: '',
      idempotency_key: '',
      metadata: {},
      payment_authorized_at: '',
      payment_id: '',
      payment_session: {},
      region_id: '',
      shipping_address_id: '',
      type: '',
      updated_at: '',
      billing_address: {},
      shipping_address: {},
      items: [],
      region: {},
      discounts: [],
      gift_cards: [],
      customer: {},
      payment_sessions: [],
      payment: {},
      shipping_methods: [],
      sales_channel_id: '',
      sales_channel: {},
      shipping_total: 0,
      discount_total: 0,
      raw_discount_total: 0,
      item_tax_total: 0,
      shipping_tax_total: 0,
      tax_total: 0,
      refunded_total: 0,
      total: 0,
      subtotal: 0,
      refundable_amount: 0,
      gift_card_total: 0,
      gift_card_tax_total: 0,
    },

    customer: {
      billing_address_id: '',
      created_at: '',
      deleted_at: '',
      email: '',
      first_name: '',
      has_account: false,
      id: '',
      last_name: '',
      metadata: {},
      phone: '',
      updated_at: '',
      billing_address: {},
      shipping_addresses: [],
      orders: [],
      groups: [],
    },
    discounts: [],
  }),
  actions: {
    setCustomer(customer) {
      this.customer = customer;
    },
    setDeliveryCart(newCart) {
      this.cart_delivery = newCart;
    },
    setPickupCart(newCart) {
      this.cart_pickup = newCart;
    },
    setDiscounts(discountArray) {
      this.discounts = discountArray;
    },
  },
});
